FROM ruby:3-alpine

ARG USER_ID=1000
ARG GROUP_ID=1000

ENV BUNDLE_PATH=/bundle \
  BUNDLE_BIN=/bundle/bin \
  GEM_HOME=/bundle

RUN apk update \
  && apk add --no-cache \
    ca-certificates \
    curl \
    tzdata \
    git \
    build-base \
    linux-headers \
    bash \
    sudo \
    coreutils \
  && addgroup -g ${GROUP_ID} app \
  && adduser -s /bin/ash -u ${USER_ID} -G app -h /home/app -S -D app \
  && mkdir /app && chown -R app:app /app \
  && mkdir /bundle \
  && chown -R app:app /bundle \
  && echo "app ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

ENV PATH="$BUNDLE_BIN:$PATH"

USER app

WORKDIR /app
