#!/bin/bash

DIR="$(cd "$(dirname "$0")" && pwd)"

if [[ $1 == --root ]] ; then
  runner="\$DIR/run --root"
  command=$2
  shift 1
else
  runner="\$DIR/run"
  command=$1
fi

cat >$DIR/$command <<EOL
#!/bin/bash

DIR="\$(cd "\$(dirname "\$0")" && pwd)"

. $runner $@ \$@
EOL

chmod +x $DIR/$command