#!/bin/bash

user=""

if [[ $1 == --root ]] ; then
  user="--user root"
  shift 1
fi

if docker-compose ps -a | grep -E -i -q 'app(\s*)running'; then
  USER_ID=$(id -u) GROUP_ID=$(id -g) docker-compose exec $user app "$@"
else
  USER_ID=$(id -u) GROUP_ID=$(id -g) docker-compose run --rm $user --service-ports app "$@"
fi